### ISSUE TITLE
angular: calling `location.back()` causes slides to go back 1 slide

### ISSUE THREAD

**Issue by NathanWalker** [TheOriginalJosh/nativescript-slides#50] opened 2016-07-07 17:12 UTC
Not sure if this is expected or not but I've noticed that if you display the slides on a navigated route (meaning you call `this._router.navigate(['/slides'])` for instance), then swipe through the slides, when you call `location.back()` it causes the slides to go back 1 slide (in addition to navigating the route back).

This is interesting behavior and not sure if there's something here that is responding to nav changes somehow?

**Comment by TheOriginalJosh** [comment] 2016-07-07 17:15
@NathanWalker that's really odd. There isn't anything that should do that... I had thought about implementing logic so if the android back button was pressed it would go back one slide though

**Comment by NathanWalker** [comment] 2016-07-07 17:38
It is rather odd; I was looking through the code and nothing jumps out but I'll try to investigate deeper soon. Strange one.

**Comment by TheOriginalJosh** [comment] 2016-07-29 00:30
I'm going to close this since it's expected behaviour with navigating in ios, and is more of an illusion. thanks man!

**Closed by TheOriginalJosh** 2016-07-29 00:30 UTC
